# Site settings
title: George Marriott
description: Digital content straight from my thoughts.
keywords: George, Blogging, Sleek
author: gmarriott
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
